// <auto-generated />
using System;
using FinanceTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTracker.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260307065151_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4A90E2",
                            Icon = "🏦",
                            InitialBalance = 4383.67m,
                            Name = "Salary Account"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#50E3C2",
                            Icon = "💰",
                            InitialBalance = 55.39m,
                            Name = "Spending Account"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#D0021B",
                            Icon = "💳",
                            InitialBalance = 4399.01m,
                            Name = "Savings Account"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#3b82f6",
                            Icon = "💰",
                            InitialBalance = 0m,
                            Name = "Investments"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF5733",
                            Icon = "🍔",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#33FF57",
                            Icon = "🚗",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#16A34A",
                            Icon = "🛒",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#F333FF",
                            Icon = "🎬",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#33FFFF",
                            Icon = "💰",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#1E3A8A",
                            Icon = "🏦",
                            Name = "Divident"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#1E3A8A",
                            Icon = "💳",
                            Name = "Emi"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#DC2626",
                            Icon = "⛽",
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#D4AF37",
                            Icon = "⚪",
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#7C3AED",
                            Icon = "💖",
                            Name = "Mother"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#E11D48",
                            Icon = "🎁",
                            Name = "Gift"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#059669",
                            Icon = "💸",
                            Name = "Cashback"
                        },
                        new
                        {
                            Id = 13,
                            Color = "#2563EB",
                            Icon = "💪",
                            Name = "Gym"
                        },
                        new
                        {
                            Id = 14,
                            Color = "#0EA5E9",
                            Icon = "📱",
                            Name = "Recharge"
                        },
                        new
                        {
                            Id = 15,
                            Color = "#047857",
                            Icon = "📈",
                            Name = "SIP"
                        },
                        new
                        {
                            Id = 16,
                            Color = "#F97316",
                            Icon = "🍫",
                            Name = "Vending machine"
                        },
                        new
                        {
                            Id = 17,
                            Color = "#7C2D12",
                            Icon = "☕",
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ToAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ToAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceTracker.Models.Transaction", b =>
                {
                    b.HasOne("FinanceTracker.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceTracker.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("FinanceTracker.Models.Account", "ToAccount")
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("ToAccount");
                });

            modelBuilder.Entity("FinanceTracker.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceTracker.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
